services:
  ticket_db:
    image: mongo:latest
    container_name: ticket_db
    ports:
      - "27017:27017"

  user_db:
    image: mongo:latest
    container_name: user_db
    ports:
      - "27018:27017"

  ticket_service:
    build: ./ticket_service
    container_name: ticket_service
    ports:
      - "8000:8000"
    depends_on:
      - ticket_db

  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8001:8000"
    depends_on:
      - user_db

  dispatcher:
    build: ./dispatcher
    container_name: dispatcher
    ports:
      - "8002:8000"
    depends_on:
      - ticket_service
      - user_service
