# özel local ağ
networks:
  yazlab_net:
    driver: bridge

services:
  ticket_db:
    image: mongo:latest
    container_name: ticket_db
    networks:
      - yazlab_net

  user_db:
    image: mongo:latest
    container_name: user_db
    networks:
      - yazlab_net
  
  auth_db:
    image: mongo:latest
    container_name: auth_db
    networks:
      - yazlab_net

  ticket_service:
    build: ./ticket_service
    container_name: ticket_service
    depends_on:
      - ticket_db
    networks:
      - yazlab_net

  user_service:
    build: ./user_service
    container_name: user_service
    depends_on:
      - user_db
    networks:
      - yazlab_net

  auth_service:
    build: ./auth_service
    container_name: auth_service
    environment:
      - MONGO_URL=mongodb://auth_db:27017
    depends_on:
      - auth_db  # ayağa kalkmadan önce db'yi bekler
    networks:
      - yazlab_net

  dispatcher:
    build: ./dispatcher
    container_name: dispatcher
    ports:
      - "8002:8000" # dışarıya açık tek yer
    depends_on:
      - ticket_service
      - user_service
      - auth_service
    networks:
      - yazlab_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # monitoring için açık olmalı
    depends_on:
      - dispatcher
    networks:
      - yazlab_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # monitoring için açık olmalı
    depends_on:
      - prometheus
    networks:
      - yazlab_net
